docker:
  image: yegor256/java8
env:
  JAVA_OPTS: -XX:MaxPermSize=256m -Xmx1g
install: |
  sudo gem install --no-rdoc --no-ri pdd
architect:
- g4s8
merge:
  script: |
    ./gradlew clean test
    pdd --source=$(pwd) --verbose --file=/dev/null
